// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// DataSet is the predicate function for dataset builders.
type DataSet func(*sql.Selector)

// TypeConfig is the predicate function for typeconfig builders.
type TypeConfig func(*sql.Selector)
