// Code generated by entc, DO NOT EDIT.

package model

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maxiloEmmmm/diy-datav/pkg/model/assets"
	"github.com/maxiloEmmmm/diy-datav/pkg/model/view"
)

// AssetsCreate is the builder for creating a Assets entity.
type AssetsCreate struct {
	config
	mutation *AssetsMutation
	hooks    []Hook
}

// SetPath sets the "path" field.
func (ac *AssetsCreate) SetPath(s string) *AssetsCreate {
	ac.mutation.SetPath(s)
	return ac
}

// SetExt sets the "ext" field.
func (ac *AssetsCreate) SetExt(s string) *AssetsCreate {
	ac.mutation.SetExt(s)
	return ac
}

// SetType sets the "type" field.
func (ac *AssetsCreate) SetType(s string) *AssetsCreate {
	ac.mutation.SetType(s)
	return ac
}

// AddViewIDs adds the "view" edge to the View entity by IDs.
func (ac *AssetsCreate) AddViewIDs(ids ...int) *AssetsCreate {
	ac.mutation.AddViewIDs(ids...)
	return ac
}

// AddView adds the "view" edges to the View entity.
func (ac *AssetsCreate) AddView(v ...*View) *AssetsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return ac.AddViewIDs(ids...)
}

// Mutation returns the AssetsMutation object of the builder.
func (ac *AssetsCreate) Mutation() *AssetsMutation {
	return ac.mutation
}

// Save creates the Assets in the database.
func (ac *AssetsCreate) Save(ctx context.Context) (*Assets, error) {
	var (
		err  error
		node *Assets
	)
	if len(ac.hooks) == 0 {
		if err = ac.check(); err != nil {
			return nil, err
		}
		node, err = ac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AssetsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ac.check(); err != nil {
				return nil, err
			}
			ac.mutation = mutation
			node, err = ac.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(ac.hooks) - 1; i >= 0; i-- {
			mut = ac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AssetsCreate) SaveX(ctx context.Context) *Assets {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (ac *AssetsCreate) check() error {
	if _, ok := ac.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New("model: missing required field \"path\"")}
	}
	if _, ok := ac.mutation.Ext(); !ok {
		return &ValidationError{Name: "ext", err: errors.New("model: missing required field \"ext\"")}
	}
	if _, ok := ac.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New("model: missing required field \"type\"")}
	}
	return nil
}

func (ac *AssetsCreate) sqlSave(ctx context.Context) (*Assets, error) {
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ac *AssetsCreate) createSpec() (*Assets, *sqlgraph.CreateSpec) {
	var (
		_node = &Assets{config: ac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: assets.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: assets.FieldID,
			},
		}
	)
	if value, ok := ac.mutation.Path(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: assets.FieldPath,
		})
		_node.Path = value
	}
	if value, ok := ac.mutation.Ext(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: assets.FieldExt,
		})
		_node.Ext = value
	}
	if value, ok := ac.mutation.GetType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: assets.FieldType,
		})
		_node.Type = value
	}
	if nodes := ac.mutation.ViewIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   assets.ViewTable,
			Columns: []string{assets.ViewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: view.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AssetsCreateBulk is the builder for creating many Assets entities in bulk.
type AssetsCreateBulk struct {
	config
	builders []*AssetsCreate
}

// Save creates the Assets entities in the database.
func (acb *AssetsCreateBulk) Save(ctx context.Context) ([]*Assets, error) {
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Assets, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AssetsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AssetsCreateBulk) SaveX(ctx context.Context) []*Assets {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
