// Code generated by entc, DO NOT EDIT.

package model

import (
	"context"
	"fmt"
	"log"

	"github.com/maxiloEmmmm/diy-datav/pkg/model/migrate"
	"github.com/maxiloEmmmm/diy-datav/pkg/model/schema"

	"github.com/maxiloEmmmm/diy-datav/pkg/model/dataset"
	"github.com/maxiloEmmmm/diy-datav/pkg/model/typeconfig"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// DataSet is the client for interacting with the DataSet builders.
	DataSet *DataSetClient
	// TypeConfig is the client for interacting with the TypeConfig builders.
	TypeConfig *TypeConfigClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.DataSet = NewDataSetClient(c.config)
	c.TypeConfig = NewTypeConfigClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("model: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("model: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:        ctx,
		config:     cfg,
		DataSet:    NewDataSetClient(cfg),
		TypeConfig: NewTypeConfigClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		config:     cfg,
		DataSet:    NewDataSetClient(cfg),
		TypeConfig: NewTypeConfigClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		DataSet.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.DataSet.Use(hooks...)
	c.TypeConfig.Use(hooks...)
}

// DataSetClient is a client for the DataSet schema.
type DataSetClient struct {
	config
}

// NewDataSetClient returns a client for the DataSet from the given config.
func NewDataSetClient(c config) *DataSetClient {
	return &DataSetClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `dataset.Hooks(f(g(h())))`.
func (c *DataSetClient) Use(hooks ...Hook) {
	c.hooks.DataSet = append(c.hooks.DataSet, hooks...)
}

// Create returns a create builder for DataSet.
func (c *DataSetClient) Create() *DataSetCreate {
	mutation := newDataSetMutation(c.config, OpCreate)
	return &DataSetCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of DataSet entities.
func (c *DataSetClient) CreateBulk(builders ...*DataSetCreate) *DataSetCreateBulk {
	return &DataSetCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for DataSet.
func (c *DataSetClient) Update() *DataSetUpdate {
	mutation := newDataSetMutation(c.config, OpUpdate)
	return &DataSetUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *DataSetClient) UpdateOne(ds *DataSet) *DataSetUpdateOne {
	mutation := newDataSetMutation(c.config, OpUpdateOne, withDataSet(ds))
	return &DataSetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *DataSetClient) UpdateOneID(id int) *DataSetUpdateOne {
	mutation := newDataSetMutation(c.config, OpUpdateOne, withDataSetID(id))
	return &DataSetUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for DataSet.
func (c *DataSetClient) Delete() *DataSetDelete {
	mutation := newDataSetMutation(c.config, OpDelete)
	return &DataSetDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *DataSetClient) DeleteOne(ds *DataSet) *DataSetDeleteOne {
	return c.DeleteOneID(ds.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *DataSetClient) DeleteOneID(id int) *DataSetDeleteOne {
	builder := c.Delete().Where(dataset.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &DataSetDeleteOne{builder}
}

// Query returns a query builder for DataSet.
func (c *DataSetClient) Query() *DataSetQuery {
	return &DataSetQuery{
		config: c.config,
	}
}

// Get returns a DataSet entity by its id.
func (c *DataSetClient) Get(ctx context.Context, id int) (*DataSet, error) {
	return c.Query().Where(dataset.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *DataSetClient) GetX(ctx context.Context, id int) *DataSet {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *DataSetClient) Hooks() []Hook {
	return c.hooks.DataSet
}

// TypeConfigClient is a client for the TypeConfig schema.
type TypeConfigClient struct {
	config
}

// NewTypeConfigClient returns a client for the TypeConfig from the given config.
func NewTypeConfigClient(c config) *TypeConfigClient {
	return &TypeConfigClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `typeconfig.Hooks(f(g(h())))`.
func (c *TypeConfigClient) Use(hooks ...Hook) {
	c.hooks.TypeConfig = append(c.hooks.TypeConfig, hooks...)
}

// Create returns a create builder for TypeConfig.
func (c *TypeConfigClient) Create() *TypeConfigCreate {
	mutation := newTypeConfigMutation(c.config, OpCreate)
	return &TypeConfigCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TypeConfig entities.
func (c *TypeConfigClient) CreateBulk(builders ...*TypeConfigCreate) *TypeConfigCreateBulk {
	return &TypeConfigCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TypeConfig.
func (c *TypeConfigClient) Update() *TypeConfigUpdate {
	mutation := newTypeConfigMutation(c.config, OpUpdate)
	return &TypeConfigUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TypeConfigClient) UpdateOne(tc *TypeConfig) *TypeConfigUpdateOne {
	mutation := newTypeConfigMutation(c.config, OpUpdateOne, withTypeConfig(tc))
	return &TypeConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TypeConfigClient) UpdateOneID(id schema.TypeKey) *TypeConfigUpdateOne {
	mutation := newTypeConfigMutation(c.config, OpUpdateOne, withTypeConfigID(id))
	return &TypeConfigUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TypeConfig.
func (c *TypeConfigClient) Delete() *TypeConfigDelete {
	mutation := newTypeConfigMutation(c.config, OpDelete)
	return &TypeConfigDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TypeConfigClient) DeleteOne(tc *TypeConfig) *TypeConfigDeleteOne {
	return c.DeleteOneID(tc.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TypeConfigClient) DeleteOneID(id schema.TypeKey) *TypeConfigDeleteOne {
	builder := c.Delete().Where(typeconfig.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TypeConfigDeleteOne{builder}
}

// Query returns a query builder for TypeConfig.
func (c *TypeConfigClient) Query() *TypeConfigQuery {
	return &TypeConfigQuery{
		config: c.config,
	}
}

// Get returns a TypeConfig entity by its id.
func (c *TypeConfigClient) Get(ctx context.Context, id schema.TypeKey) (*TypeConfig, error) {
	return c.Query().Where(typeconfig.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TypeConfigClient) GetX(ctx context.Context, id schema.TypeKey) *TypeConfig {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TypeConfigClient) Hooks() []Hook {
	return c.hooks.TypeConfig
}
