// Code generated by entc, DO NOT EDIT.

package model

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/maxiloEmmmm/diy-datav/pkg/model/dataset"
	"github.com/maxiloEmmmm/diy-datav/pkg/model/predicate"
	"github.com/maxiloEmmmm/diy-datav/pkg/model/view"
	"github.com/maxiloEmmmm/diy-datav/pkg/model/viewblock"
)

// ViewBlockQuery is the builder for querying ViewBlock entities.
type ViewBlockQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.ViewBlock
	// eager-loading edges.
	withView    *ViewQuery
	withDataset *DataSetQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ViewBlockQuery builder.
func (vbq *ViewBlockQuery) Where(ps ...predicate.ViewBlock) *ViewBlockQuery {
	vbq.predicates = append(vbq.predicates, ps...)
	return vbq
}

// Limit adds a limit step to the query.
func (vbq *ViewBlockQuery) Limit(limit int) *ViewBlockQuery {
	vbq.limit = &limit
	return vbq
}

// Offset adds an offset step to the query.
func (vbq *ViewBlockQuery) Offset(offset int) *ViewBlockQuery {
	vbq.offset = &offset
	return vbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (vbq *ViewBlockQuery) Unique(unique bool) *ViewBlockQuery {
	vbq.unique = &unique
	return vbq
}

// Order adds an order step to the query.
func (vbq *ViewBlockQuery) Order(o ...OrderFunc) *ViewBlockQuery {
	vbq.order = append(vbq.order, o...)
	return vbq
}

// QueryView chains the current query on the "view" edge.
func (vbq *ViewBlockQuery) QueryView() *ViewQuery {
	query := &ViewQuery{config: vbq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vbq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(viewblock.Table, viewblock.FieldID, selector),
			sqlgraph.To(view.Table, view.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, viewblock.ViewTable, viewblock.ViewColumn),
		)
		fromU = sqlgraph.SetNeighbors(vbq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDataset chains the current query on the "dataset" edge.
func (vbq *ViewBlockQuery) QueryDataset() *DataSetQuery {
	query := &DataSetQuery{config: vbq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := vbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := vbq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(viewblock.Table, viewblock.FieldID, selector),
			sqlgraph.To(dataset.Table, dataset.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, viewblock.DatasetTable, viewblock.DatasetColumn),
		)
		fromU = sqlgraph.SetNeighbors(vbq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ViewBlock entity from the query.
// Returns a *NotFoundError when no ViewBlock was found.
func (vbq *ViewBlockQuery) First(ctx context.Context) (*ViewBlock, error) {
	nodes, err := vbq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{viewblock.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (vbq *ViewBlockQuery) FirstX(ctx context.Context) *ViewBlock {
	node, err := vbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ViewBlock ID from the query.
// Returns a *NotFoundError when no ViewBlock ID was found.
func (vbq *ViewBlockQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vbq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{viewblock.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (vbq *ViewBlockQuery) FirstIDX(ctx context.Context) int {
	id, err := vbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ViewBlock entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one ViewBlock entity is not found.
// Returns a *NotFoundError when no ViewBlock entities are found.
func (vbq *ViewBlockQuery) Only(ctx context.Context) (*ViewBlock, error) {
	nodes, err := vbq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{viewblock.Label}
	default:
		return nil, &NotSingularError{viewblock.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (vbq *ViewBlockQuery) OnlyX(ctx context.Context) *ViewBlock {
	node, err := vbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ViewBlock ID in the query.
// Returns a *NotSingularError when exactly one ViewBlock ID is not found.
// Returns a *NotFoundError when no entities are found.
func (vbq *ViewBlockQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = vbq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = &NotSingularError{viewblock.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (vbq *ViewBlockQuery) OnlyIDX(ctx context.Context) int {
	id, err := vbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ViewBlocks.
func (vbq *ViewBlockQuery) All(ctx context.Context) ([]*ViewBlock, error) {
	if err := vbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return vbq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (vbq *ViewBlockQuery) AllX(ctx context.Context) []*ViewBlock {
	nodes, err := vbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ViewBlock IDs.
func (vbq *ViewBlockQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := vbq.Select(viewblock.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (vbq *ViewBlockQuery) IDsX(ctx context.Context) []int {
	ids, err := vbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (vbq *ViewBlockQuery) Count(ctx context.Context) (int, error) {
	if err := vbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return vbq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (vbq *ViewBlockQuery) CountX(ctx context.Context) int {
	count, err := vbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (vbq *ViewBlockQuery) Exist(ctx context.Context) (bool, error) {
	if err := vbq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return vbq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (vbq *ViewBlockQuery) ExistX(ctx context.Context) bool {
	exist, err := vbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ViewBlockQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (vbq *ViewBlockQuery) Clone() *ViewBlockQuery {
	if vbq == nil {
		return nil
	}
	return &ViewBlockQuery{
		config:      vbq.config,
		limit:       vbq.limit,
		offset:      vbq.offset,
		order:       append([]OrderFunc{}, vbq.order...),
		predicates:  append([]predicate.ViewBlock{}, vbq.predicates...),
		withView:    vbq.withView.Clone(),
		withDataset: vbq.withDataset.Clone(),
		// clone intermediate query.
		sql:  vbq.sql.Clone(),
		path: vbq.path,
	}
}

// WithView tells the query-builder to eager-load the nodes that are connected to
// the "view" edge. The optional arguments are used to configure the query builder of the edge.
func (vbq *ViewBlockQuery) WithView(opts ...func(*ViewQuery)) *ViewBlockQuery {
	query := &ViewQuery{config: vbq.config}
	for _, opt := range opts {
		opt(query)
	}
	vbq.withView = query
	return vbq
}

// WithDataset tells the query-builder to eager-load the nodes that are connected to
// the "dataset" edge. The optional arguments are used to configure the query builder of the edge.
func (vbq *ViewBlockQuery) WithDataset(opts ...func(*DataSetQuery)) *ViewBlockQuery {
	query := &DataSetQuery{config: vbq.config}
	for _, opt := range opts {
		opt(query)
	}
	vbq.withDataset = query
	return vbq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ViewBlock.Query().
//		GroupBy(viewblock.FieldType).
//		Aggregate(model.Count()).
//		Scan(ctx, &v)
//
func (vbq *ViewBlockQuery) GroupBy(field string, fields ...string) *ViewBlockGroupBy {
	group := &ViewBlockGroupBy{config: vbq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := vbq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return vbq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.ViewBlock.Query().
//		Select(viewblock.FieldType).
//		Scan(ctx, &v)
//
func (vbq *ViewBlockQuery) Select(field string, fields ...string) *ViewBlockSelect {
	vbq.fields = append([]string{field}, fields...)
	return &ViewBlockSelect{ViewBlockQuery: vbq}
}

func (vbq *ViewBlockQuery) prepareQuery(ctx context.Context) error {
	for _, f := range vbq.fields {
		if !viewblock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("model: invalid field %q for query", f)}
		}
	}
	if vbq.path != nil {
		prev, err := vbq.path(ctx)
		if err != nil {
			return err
		}
		vbq.sql = prev
	}
	return nil
}

func (vbq *ViewBlockQuery) sqlAll(ctx context.Context) ([]*ViewBlock, error) {
	var (
		nodes       = []*ViewBlock{}
		withFKs     = vbq.withFKs
		_spec       = vbq.querySpec()
		loadedTypes = [2]bool{
			vbq.withView != nil,
			vbq.withDataset != nil,
		}
	)
	if vbq.withView != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, viewblock.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &ViewBlock{config: vbq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("model: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, vbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := vbq.withView; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*ViewBlock)
		for i := range nodes {
			if nodes[i].view_blocks == nil {
				continue
			}
			fk := *nodes[i].view_blocks
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(view.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "view_blocks" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.View = n
			}
		}
	}

	if query := vbq.withDataset; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*ViewBlock)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Dataset = []*DataSet{}
		}
		query.withFKs = true
		query.Where(predicate.DataSet(func(s *sql.Selector) {
			s.Where(sql.InValues(viewblock.DatasetColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.view_block_dataset
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "view_block_dataset" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "view_block_dataset" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.Dataset = append(node.Edges.Dataset, n)
		}
	}

	return nodes, nil
}

func (vbq *ViewBlockQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := vbq.querySpec()
	return sqlgraph.CountNodes(ctx, vbq.driver, _spec)
}

func (vbq *ViewBlockQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := vbq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("model: check existence: %w", err)
	}
	return n > 0, nil
}

func (vbq *ViewBlockQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   viewblock.Table,
			Columns: viewblock.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: viewblock.FieldID,
			},
		},
		From:   vbq.sql,
		Unique: true,
	}
	if unique := vbq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := vbq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, viewblock.FieldID)
		for i := range fields {
			if fields[i] != viewblock.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := vbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := vbq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := vbq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := vbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (vbq *ViewBlockQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(vbq.driver.Dialect())
	t1 := builder.Table(viewblock.Table)
	selector := builder.Select(t1.Columns(viewblock.Columns...)...).From(t1)
	if vbq.sql != nil {
		selector = vbq.sql
		selector.Select(selector.Columns(viewblock.Columns...)...)
	}
	for _, p := range vbq.predicates {
		p(selector)
	}
	for _, p := range vbq.order {
		p(selector)
	}
	if offset := vbq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := vbq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ViewBlockGroupBy is the group-by builder for ViewBlock entities.
type ViewBlockGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (vbgb *ViewBlockGroupBy) Aggregate(fns ...AggregateFunc) *ViewBlockGroupBy {
	vbgb.fns = append(vbgb.fns, fns...)
	return vbgb
}

// Scan applies the group-by query and scans the result into the given value.
func (vbgb *ViewBlockGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := vbgb.path(ctx)
	if err != nil {
		return err
	}
	vbgb.sql = query
	return vbgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := vbgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (vbgb *ViewBlockGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(vbgb.fields) > 1 {
		return nil, errors.New("model: ViewBlockGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := vbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) StringsX(ctx context.Context) []string {
	v, err := vbgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vbgb *ViewBlockGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vbgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = fmt.Errorf("model: ViewBlockGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) StringX(ctx context.Context) string {
	v, err := vbgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (vbgb *ViewBlockGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(vbgb.fields) > 1 {
		return nil, errors.New("model: ViewBlockGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := vbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) IntsX(ctx context.Context) []int {
	v, err := vbgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vbgb *ViewBlockGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vbgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = fmt.Errorf("model: ViewBlockGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) IntX(ctx context.Context) int {
	v, err := vbgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (vbgb *ViewBlockGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(vbgb.fields) > 1 {
		return nil, errors.New("model: ViewBlockGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := vbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := vbgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vbgb *ViewBlockGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vbgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = fmt.Errorf("model: ViewBlockGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) Float64X(ctx context.Context) float64 {
	v, err := vbgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (vbgb *ViewBlockGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(vbgb.fields) > 1 {
		return nil, errors.New("model: ViewBlockGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := vbgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := vbgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (vbgb *ViewBlockGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vbgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = fmt.Errorf("model: ViewBlockGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vbgb *ViewBlockGroupBy) BoolX(ctx context.Context) bool {
	v, err := vbgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vbgb *ViewBlockGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range vbgb.fields {
		if !viewblock.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := vbgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := vbgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vbgb *ViewBlockGroupBy) sqlQuery() *sql.Selector {
	selector := vbgb.sql
	columns := make([]string, 0, len(vbgb.fields)+len(vbgb.fns))
	columns = append(columns, vbgb.fields...)
	for _, fn := range vbgb.fns {
		columns = append(columns, fn(selector))
	}
	return selector.Select(columns...).GroupBy(vbgb.fields...)
}

// ViewBlockSelect is the builder for selecting fields of ViewBlock entities.
type ViewBlockSelect struct {
	*ViewBlockQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (vbs *ViewBlockSelect) Scan(ctx context.Context, v interface{}) error {
	if err := vbs.prepareQuery(ctx); err != nil {
		return err
	}
	vbs.sql = vbs.ViewBlockQuery.sqlQuery(ctx)
	return vbs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (vbs *ViewBlockSelect) ScanX(ctx context.Context, v interface{}) {
	if err := vbs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (vbs *ViewBlockSelect) Strings(ctx context.Context) ([]string, error) {
	if len(vbs.fields) > 1 {
		return nil, errors.New("model: ViewBlockSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := vbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (vbs *ViewBlockSelect) StringsX(ctx context.Context) []string {
	v, err := vbs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (vbs *ViewBlockSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = vbs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = fmt.Errorf("model: ViewBlockSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (vbs *ViewBlockSelect) StringX(ctx context.Context) string {
	v, err := vbs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (vbs *ViewBlockSelect) Ints(ctx context.Context) ([]int, error) {
	if len(vbs.fields) > 1 {
		return nil, errors.New("model: ViewBlockSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := vbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (vbs *ViewBlockSelect) IntsX(ctx context.Context) []int {
	v, err := vbs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (vbs *ViewBlockSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = vbs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = fmt.Errorf("model: ViewBlockSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (vbs *ViewBlockSelect) IntX(ctx context.Context) int {
	v, err := vbs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (vbs *ViewBlockSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(vbs.fields) > 1 {
		return nil, errors.New("model: ViewBlockSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := vbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (vbs *ViewBlockSelect) Float64sX(ctx context.Context) []float64 {
	v, err := vbs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (vbs *ViewBlockSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = vbs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = fmt.Errorf("model: ViewBlockSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (vbs *ViewBlockSelect) Float64X(ctx context.Context) float64 {
	v, err := vbs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (vbs *ViewBlockSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(vbs.fields) > 1 {
		return nil, errors.New("model: ViewBlockSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := vbs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (vbs *ViewBlockSelect) BoolsX(ctx context.Context) []bool {
	v, err := vbs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (vbs *ViewBlockSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = vbs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{viewblock.Label}
	default:
		err = fmt.Errorf("model: ViewBlockSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (vbs *ViewBlockSelect) BoolX(ctx context.Context) bool {
	v, err := vbs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (vbs *ViewBlockSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := vbs.sqlQuery().Query()
	if err := vbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (vbs *ViewBlockSelect) sqlQuery() sql.Querier {
	selector := vbs.sql
	selector.Select(selector.Columns(vbs.fields...)...)
	return selector
}
